### ISSUE TITLE
Little Question about authentication

### ISSUE THREAD

**Issue by HannahJSwystun** [yesnault/PlayStartApp#20]
Hi,

My Name is HANNAH, I would like firstable to thank the creator and all contributors (Sir.Sargent) for this nice SAMPLE AUTHENTICATION, however if I may I would like to ask you a little question : 

1) How can I change authentication with for example <fullname> instead of <email>

Thank you so much.

**Comment by yesnault** [comment]
Sorry, I don't understand the question

**Comment by HannahJSwystun** [comment]
I would like to authenticate with fullname instead of email

Le 21 janv. 2017 4:32 PM, "Yvonnick Esnault" <notifications@github.com> a
écrit :

**Comment by HannahJSwystun** [comment]
How to...please

**Comment by yesnault** [comment]
you have to do something here: 
https://github.com/yesnault/PlayStartApp/blob/master/app/models/User.java#L90
https://github.com/yesnault/PlayStartApp/blob/master/app/controllers/Secured.java#L15
https://github.com/yesnault/PlayStartApp/blob/master/app/controllers/Application.java#L69
https://github.com/yesnault/PlayStartApp/blob/master/app/controllers/Application.java#L133
